Repository drashland/deno-drash-middleware, pull requests merged in 2020-12, with the labels that each got.

#84 chore: Clean up paladin function
  paladin/mod.ts
Labels: Type: Chore

#90 fix(serve_typescript): Use Deno.bundle instead; Add error logging
  .github/workflows/master.yml
  console/bumper_ci_service_files.ts
  dexter/mod.ts
  dexter/tests/mod_test.ts
  paladin/tests/mod_test.ts
  serve_typescript/mod.ts
  serve_typescript/tests/data/invalid_ts.ts
  serve_typescript/tests/data/my_ts.ts
  serve_typescript/tests/mod_test.ts
  tengine/jae.ts
  tengine/tests/mod_test.ts
  test_deps.ts
Labels: Type: Patch

#1 feat: added cors middleware
   LICENSE
  .github/workflows/master.yml
  README.md
  console/bumper_ci_service_files.ts
  cors/README.md
  cors/deps.ts
  cors/mod.ts
  cors/tests/mod_test.ts
Labels: Type: Minor
