Repository drashland/deno-drash-middleware, pull requests merged in 2020-11, with the labels that each got.

#60 feat: ServeTypeScript - Write front-end TypeScript
  README.md
  csrf/README.md
  dexter/README.md
  egg.json
  paladin/README.md
  serve_typescript/README.md
  serve_typescript/mod.ts
  serve_typescript/tests/data/my_ts.ts
  serve_typescript/tests/mod_test.ts
  test_deps.ts
Labels: Type: Minor

#63 chore: Complete ci
  .github/workflows/bumper.yml
  .github/workflows/pre_release.yml
  .github/workflows/release.yml
  console/bumper_ci_service.ts
  console/bumper_ci_service_files.ts
  console/update_dependency_version_strings.ts
  mod.ts
Labels: Remark: Approved, Type: Patch

#62 feat: Tengine - A template engine middleware
  README.md
  tengine/README.md
  tengine/jae.ts
  tengine/mod.ts
  tengine/tests/mod_test.ts
  tengine/tests/views/index.html
Labels: Type: Minor

#70 chore: Add tweets and reddit post to release workflow
  .github/workflows/pre_release.yml
  .github/workflows/release.yml
Labels: Remark: Approved, Type: Chore

#72 fix: tengine incorrectly referencing Drash
  tengine/README.md
  tengine/mod.ts
Labels: Type: Patch

#73 chore: update pre-release and release CI processes
  .github/workflows/pre_release.yml
  .github/workflows/release.yml
Labels: Type: Chore

#83 fix(csrf): throw 400 for no token and 403 for unmatched token
  csrf/mod.ts
  csrf/tests/mod_test.ts
Labels: Type: Patch

#86 chore: Reduce bloat
  .github/workflows/master.yml
  console/bumper_ci_service_files.ts
Labels: Type: Chore
